import { WorkspaceState } from "@/components/workspace/types";

// Estado inicial do workspace para primeiro acesso.
export const initialWorkspace: WorkspaceState = {
  activeProjectId: "proj-ops",
  currentUserId: "user-raphael",
  users: [
    { id: "user-raphael", name: "Raphael", email: "raphael@agiliza.ai", password: "agiliza123", role: "owner", active: true },
    { id: "user-ana", name: "Ana", email: "ana@agiliza.ai", password: "agiliza123", role: "admin", active: true },
    { id: "user-bruno", name: "Bruno", email: "bruno@agiliza.ai", password: "agiliza123", role: "member", active: true },
    { id: "user-camila", name: "Camila", email: "camila@agiliza.ai", password: "agiliza123", role: "member", active: true },
    { id: "user-diego", name: "Diego", email: "diego@agiliza.ai", password: "agiliza123", role: "viewer", active: true },
  ],
  teams: [
    {
      id: "team-ops",
      name: "Operacoes",
      description: "Time responsavel por suporte e fluxo diario.",
      memberIds: ["user-raphael", "user-ana", "user-bruno"],
    },
    {
      id: "team-prod",
      name: "Produto",
      description: "Planejamento, UX e entrega do roadmap.",
      memberIds: ["user-raphael", "user-camila", "user-diego"],
    },
  ],
  inbox: [
    {
      id: "inbox-1",
      title: "Mencao em tarefa",
      description: "Ana mencionou voce em \"Refinar playbook de atendimento\".",
      createdAt: "2026-03-23",
      read: false,
      kind: "mention",
    },
    {
      id: "inbox-2",
      title: "Prazo proximo",
      description: "\"Consolidar dashboard semanal\" vence amanha.",
      createdAt: "2026-03-23",
      read: false,
      kind: "deadline",
    },
  ],
  helpCenter: [
    {
      id: "help-1",
      title: "Como criar tarefas rapidamente",
      content: "Use o campo \"Nova tarefa\" no topo do board e preencha prioridade, prazo e responsavel.",
      category: "tasks",
    },
    {
      id: "help-2",
      title: "Como organizar times e usuarios",
      content: "Abra o menu de perfil e utilize \"Gestao de time\" para cadastrar membros e criar times.",
      category: "teams",
    },
    {
      id: "help-3",
      title: "Primeiros passos",
      content: "Crie um projeto, adicione tarefas no backlog e mova entre colunas conforme o progresso.",
      category: "getting_started",
    },
  ],
  projects: [
    {
      id: "proj-ops",
      name: "Operacao",
      description: "Fluxo diario da equipe de operacoes.",
      accent: "from-cyan-300 to-blue-400",
      tasks: [
        {
          id: "task-1",
          title: "Refinar playbook de atendimento",
          description: "Padronizar respostas para tickets com SLA de 4h.",
          status: "in_progress",
          priority: "high",
          dueDate: "2026-03-18",
          assignee: "Ana",
          marker: "rose",
          checklist: [
            { id: "sub-1", title: "Revisar base de respostas", done: true },
            { id: "sub-2", title: "Validar fluxo com lider", done: false },
          ],
          blockedBy: [],
          comments: [
            {
              id: "c-1",
              author: "Raphael",
              text: "Validar com @Ana e @Bruno antes da publicacao.",
              createdAt: "2026-03-16",
              mentions: ["Ana", "Bruno"],
            },
          ],
          activity: ["2026-03-15: tarefa criada"],
          labels: ["SLA", "Suporte"],
          createdAt: "2026-03-15",
          updatedAt: "2026-03-16",
        },
        {
          id: "task-2",
          title: "Consolidar dashboard semanal",
          description: "Unificar metricas de volume, tempo medio e backlog.",
          status: "review",
          priority: "medium",
          dueDate: "2026-03-19",
          assignee: "Bruno",
          marker: "amber",
          checklist: [{ id: "sub-3", title: "Consolidar metricas BI", done: true }],
          blockedBy: ["task-1"],
          comments: [],
          activity: ["2026-03-14: tarefa criada"],
          labels: ["BI", "KPI"],
          createdAt: "2026-03-14",
          updatedAt: "2026-03-16",
        },
        {
          id: "task-3",
          title: "Atualizar base de macros",
          description: "Remover templates antigos e validar 12 novos atalhos.",
          status: "backlog",
          priority: "low",
          dueDate: "",
          assignee: "Camila",
          marker: "sky",
          checklist: [],
          blockedBy: [],
          comments: [],
          activity: ["2026-03-13: tarefa criada"],
          labels: ["Base"],
          createdAt: "2026-03-13",
          updatedAt: "2026-03-13",
        },
      ],
    },
    {
      id: "proj-product",
      name: "Produto",
      description: "Roadmap e desenvolvimento do Agiliza Ai.",
      accent: "from-emerald-300 to-cyan-400",
      tasks: [
        {
          id: "task-4",
          title: "Definir onboarding inteligente",
          description: "Primeira experiencia com sugestoes de projeto por perfil.",
          status: "backlog",
          priority: "high",
          dueDate: "2026-03-22",
          assignee: "Raphael",
          marker: "violet",
          checklist: [{ id: "sub-4", title: "Mapear perfis de usuario", done: false }],
          blockedBy: [],
          comments: [],
          activity: ["2026-03-15: tarefa criada"],
          labels: ["UX", "IA"],
          createdAt: "2026-03-15",
          updatedAt: "2026-03-16",
        },
        {
          id: "task-5",
          title: "Tela de relatorios executivos",
          description: "Visao consolidada para lideranca com indicadores de entrega.",
          status: "done",
          priority: "medium",
          dueDate: "2026-03-16",
          assignee: "Diego",
          marker: "emerald",
          checklist: [],
          blockedBy: [],
          comments: [],
          activity: ["2026-03-13: tarefa criada", "2026-03-16: marcada como concluida"],
          labels: ["Dashboard"],
          createdAt: "2026-03-13",
          updatedAt: "2026-03-16",
        },
      ],
    },
  ],
};

