import { WorkspaceState } from "@/components/workspace/types";

// Estado inicial do workspace para primeiro acesso.
export const initialWorkspace: WorkspaceState = {
  activeProjectId: "proj-ops",
  projects: [
    {
      id: "proj-ops",
      name: "Operacao",
      description: "Fluxo diario da equipe de operacoes.",
      accent: "from-cyan-300 to-blue-400",
      tasks: [
        {
          id: "task-1",
          title: "Refinar playbook de atendimento",
          description: "Padronizar respostas para tickets com SLA de 4h.",
          status: "in_progress",
          priority: "high",
          dueDate: "2026-03-18",
          assignee: "Ana",
          marker: "rose",
          checklist: [
            { id: "sub-1", title: "Revisar base de respostas", done: true },
            { id: "sub-2", title: "Validar fluxo com lider", done: false },
          ],
          blockedBy: [],
          comments: [
            {
              id: "c-1",
              author: "Raphael",
              text: "Validar com @Ana e @Bruno antes da publicacao.",
              createdAt: "2026-03-16",
              mentions: ["Ana", "Bruno"],
            },
          ],
          activity: ["2026-03-15: tarefa criada"],
          labels: ["SLA", "Suporte"],
          createdAt: "2026-03-15",
          updatedAt: "2026-03-16",
        },
        {
          id: "task-2",
          title: "Consolidar dashboard semanal",
          description: "Unificar metricas de volume, tempo medio e backlog.",
          status: "review",
          priority: "medium",
          dueDate: "2026-03-19",
          assignee: "Bruno",
          marker: "amber",
          checklist: [{ id: "sub-3", title: "Consolidar metricas BI", done: true }],
          blockedBy: ["task-1"],
          comments: [],
          activity: ["2026-03-14: tarefa criada"],
          labels: ["BI", "KPI"],
          createdAt: "2026-03-14",
          updatedAt: "2026-03-16",
        },
        {
          id: "task-3",
          title: "Atualizar base de macros",
          description: "Remover templates antigos e validar 12 novos atalhos.",
          status: "backlog",
          priority: "low",
          dueDate: "",
          assignee: "Camila",
          marker: "sky",
          checklist: [],
          blockedBy: [],
          comments: [],
          activity: ["2026-03-13: tarefa criada"],
          labels: ["Base"],
          createdAt: "2026-03-13",
          updatedAt: "2026-03-13",
        },
      ],
    },
    {
      id: "proj-product",
      name: "Produto",
      description: "Roadmap e desenvolvimento do Agiliza Ai.",
      accent: "from-emerald-300 to-cyan-400",
      tasks: [
        {
          id: "task-4",
          title: "Definir onboarding inteligente",
          description: "Primeira experiencia com sugestoes de projeto por perfil.",
          status: "backlog",
          priority: "high",
          dueDate: "2026-03-22",
          assignee: "Raphael",
          marker: "violet",
          checklist: [{ id: "sub-4", title: "Mapear perfis de usuario", done: false }],
          blockedBy: [],
          comments: [],
          activity: ["2026-03-15: tarefa criada"],
          labels: ["UX", "IA"],
          createdAt: "2026-03-15",
          updatedAt: "2026-03-16",
        },
        {
          id: "task-5",
          title: "Tela de relatorios executivos",
          description: "Visao consolidada para lideranca com indicadores de entrega.",
          status: "done",
          priority: "medium",
          dueDate: "2026-03-16",
          assignee: "Diego",
          marker: "emerald",
          checklist: [],
          blockedBy: [],
          comments: [],
          activity: ["2026-03-13: tarefa criada", "2026-03-16: marcada como concluida"],
          labels: ["Dashboard"],
          createdAt: "2026-03-13",
          updatedAt: "2026-03-16",
        },
      ],
    },
  ],
};

